/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PgkPresentacion;

import PkgEntidad.ClsInmuebleE;
import PkgNegocio.ClsInmuebleN;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author smoke
 */
public class FrmAgregarInmueble extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmAgregarInmuble1
     */
    public static int idusuario;
    public FrmAgregarInmueble() {
        initComponents();
        txtCodigo.setText(String.valueOf(idusuario));
        txtDireccion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CboCategoria = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnAgregarImagen = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtDescripcion = new LIB.FSTexFieldMD();
        txtCodigo = new LIB.FSTexFieldMD();
        txtDirecInmueble = new LIB.FSTexFieldMD();
        txtNroHabitaciones = new LIB.FSTexFieldMD();
        txtCiudad = new LIB.FSTexFieldMD();
        txtPrecio = new LIB.FSTexFieldMD();
        jLImg = new LIB.JEImagePanel();
        txtDireccion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ciudad: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Precio:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Descripcion: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, 20));

        CboCategoria.setBackground(new java.awt.Color(48, 93, 197));
        CboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento", "mansion" }));
        jPanel1.add(CboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 180, 30));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 82, 30));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 81, 30));

        btnAgregarImagen.setText("Agregar Imagen");
        btnAgregarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarImagenActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 125, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Direccion Inmueble:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Codigo :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Numero de Habitaciones: ");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Categoria:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, 20));

        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtDescripcion.setBordeColorFocus(new java.awt.Color(51, 51, 255));
        txtDescripcion.setPlaceholder("Ingrese Breve Descripcion...");
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, 80));

        txtCodigo.setEditable(false);
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigo.setBordeColorFocus(new java.awt.Color(51, 51, 255));
        txtCodigo.setPlaceholder("Ingrese Codigo...");
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        txtDirecInmueble.setForeground(new java.awt.Color(0, 0, 0));
        txtDirecInmueble.setBordeColorFocus(new java.awt.Color(51, 51, 255));
        txtDirecInmueble.setPlaceholder("Ingrese la Direccion del Inmueble...");
        jPanel1.add(txtDirecInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        txtNroHabitaciones.setForeground(new java.awt.Color(0, 0, 0));
        txtNroHabitaciones.setBordeColorFocus(new java.awt.Color(51, 51, 255));
        txtNroHabitaciones.setPlaceholder("Ingrese N° de habitaciones...");
        jPanel1.add(txtNroHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        txtCiudad.setForeground(new java.awt.Color(0, 0, 0));
        txtCiudad.setBordeColorFocus(new java.awt.Color(51, 51, 255));
        txtCiudad.setPlaceholder("Ingrese la Ciudad ...");
        jPanel1.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 40));

        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecio.setBordeColorFocus(new java.awt.Color(51, 51, 255));
        txtPrecio.setPlaceholder("S/0.00");
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, 40));

        javax.swing.GroupLayout jLImgLayout = new javax.swing.GroupLayout(jLImg);
        jLImg.setLayout(jLImgLayout);
        jLImgLayout.setHorizontalGroup(
            jLImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jLImgLayout.setVerticalGroup(
            jLImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel1.add(jLImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 210, 200));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 60, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar Inmueble");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
File archivo;
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        ClsInmuebleE objInmE=new  ClsInmuebleE();
        ClsInmuebleN objInmN=new ClsInmuebleN();
        objInmE.setUsuarioid(Integer.parseInt(txtCodigo.getText()));
        objInmE.setDireccioninmueble(txtDirecInmueble.getText());
        objInmE.setEstado("Nopublicado");
        objInmE.setNrohabitaciones(Integer.parseInt(txtNroHabitaciones.getText()));
        objInmE.setCiudad(txtCiudad.getText());
        objInmE.setDescripcion(txtDescripcion.getText());
        objInmE.setCategoria((String)CboCategoria.getSelectedItem());
        objInmE.setPrecio(Double.parseDouble(txtPrecio.getText()));
        File foto = new File(txtDireccion.getText());
        try{
            byte[] icono = new byte[(int) foto.length()];
            InputStream input = new FileInputStream(foto);
            input.read(icono);
            objInmE.setFoto(icono);
        }catch(Exception ex){
            objInmE.setFoto(null);
        }
        if (objInmN.MtdRegistrarInmueble(objInmE)== true) {
            JOptionPane.showMessageDialog(null, "Dato Guardados Correctamente...");
            MtdLimpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Error de Datos...");
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        MtdLimpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarImagenActionPerformed
        // TODO add your handling code here:
        int resultado;
        FrmImagen Buscador =new FrmImagen();
        FileNameExtensionFilter formato  = new FileNameExtensionFilter("JPG, PNG y GIF", "jpg", "png", "gif");
        Buscador.JFCImg.setFileFilter(formato);
        resultado = Buscador.JFCImg.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado){
            archivo = Buscador.JFCImg.getSelectedFile();
            txtDireccion.setText(archivo.getAbsolutePath());

            try {
                ImageIcon ImgIcon = new ImageIcon(archivo.toString());
                Icon icono = new ImageIcon(ImgIcon.getImage().getScaledInstance(jLImg.getWidth(), jLImg.getHeight(),Image.SCALE_DEFAULT));
                jLImg.setIcon(icono);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Error al abrir: " + e);
            }
        }
    }//GEN-LAST:event_btnAgregarImagenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboCategoria;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarImagen;
    private javax.swing.JButton btnLimpiar;
    private LIB.JEImagePanel jLImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private LIB.FSTexFieldMD txtCiudad;
    private LIB.FSTexFieldMD txtCodigo;
    private LIB.FSTexFieldMD txtDescripcion;
    private LIB.FSTexFieldMD txtDirecInmueble;
    private javax.swing.JTextField txtDireccion;
    private LIB.FSTexFieldMD txtNroHabitaciones;
    private LIB.FSTexFieldMD txtPrecio;
    // End of variables declaration//GEN-END:variables

    private void MtdLimpiar() {
        txtCiudad.setText("");
       txtCodigo.setText("");
       txtDescripcion.setText("");
       txtDirecInmueble.setText("");
       txtNroHabitaciones.setText("");
       txtPrecio.setText("");
    }
}
