/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PgkPresentacion;

import PkgEntidad.ClsInmuebleE;
import PkgNegocio.ClsInmuebleN;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author smoke
 */
public class FrmEditarInmueble extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmEditarInmueble1
     */
     public DefaultTableModel modelo;
     public static int seleccion;
     public static JLabel Foto;
    public FrmEditarInmueble() {
        initComponents();
        tbinmueble1.setDefaultRenderer(Object.class,new RenderTabla());
        txtDireccion2.setVisible(false);
        MtdListarInmueble();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TbpPanel = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbinmueble = new javax.swing.JTable();
        ChkSeleccionar = new javax.swing.JCheckBox();
        btnEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        cboCategoria = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnSeleccionarImagen = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jEImagePanel1 = new LIB.JEImagePanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        TbpPanel1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtBuscar1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbinmueble1 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        txtDireccion1 = new javax.swing.JTextField();
        txtNumero1 = new javax.swing.JTextField();
        txtCiudad1 = new javax.swing.JTextField();
        CboCategoria = new javax.swing.JComboBox<>();
        txtPrecio1 = new javax.swing.JTextField();
        btnActualizar1 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnSeleccionarImagen1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDescripcion1 = new javax.swing.JTextArea();
        jimagen2 = new LIB.JEImagePanel();
        txtDireccion2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        jPanel2.setBackground(java.awt.SystemColor.window);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TbpPanel.setBorder(new javax.swing.border.MatteBorder(null));
        TbpPanel.setName("editar"); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Buscar:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 252, -1));

        btnBuscar.setText("Buscar");
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        tbinmueble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbinmueble);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 780, 260));

        ChkSeleccionar.setText("Seleccionar");
        jPanel3.add(ChkSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        btnEliminar.setText("Eliminar");
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        jLabel3.setText("Total:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, -1, -1));

        TbpPanel.addTab("Listar", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Id Inmueble :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel5.setText("Direccion     :");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel6.setText("Numero      :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel7.setText("Ciudad       :");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel8.setText("Categoria   :");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel9.setText("Precio          :  ");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel10.setText("Descripcion  :");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));
        jPanel4.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 90, -1));
        jPanel4.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 240, -1));
        jPanel4.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, -1));
        jPanel4.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 90, -1));

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(cboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 90, -1));
        jPanel4.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 90, -1));

        btnActualizar.setText("Actualizar");
        jPanel4.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        btnCancelar.setText("Cancelar");
        jPanel4.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jPanel5.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 40, -1, -1));

        btnSeleccionarImagen.setText("Seleccionar Imagen");
        jPanel4.add(btnSeleccionarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane4.setViewportView(txtDescripcion);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 244, -1));

        jEImagePanel1.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jEImagePanel1Layout = new javax.swing.GroupLayout(jEImagePanel1);
        jEImagePanel1.setLayout(jEImagePanel1Layout);
        jEImagePanel1Layout.setHorizontalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        jEImagePanel1Layout.setVerticalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanel4.add(jEImagePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 210, 190));

        TbpPanel.addTab("Editar", jPanel4);

        jPanel2.add(TbpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 900, 450));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar Inmueble");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel6.setBackground(java.awt.SystemColor.window);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TbpPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        TbpPanel1.setName("editar"); // NOI18N

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Buscar:");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        txtBuscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscar1KeyTyped(evt);
            }
        });
        jPanel7.add(txtBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 252, -1));

        tbinmueble1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbinmueble1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbinmueble1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbinmueble1);

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 670, 260));

        TbpPanel1.addTab("Listar", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Id Inmueble :");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel14.setText("Direccion     :");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel15.setText("Numero      :");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel16.setText("Ciudad       :");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel17.setText("Categoria   :");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel18.setText("Precio          :  ");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel19.setText("Descripcion  :");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        txtId1.setEditable(false);
        jPanel8.add(txtId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 90, -1));
        jPanel8.add(txtDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 240, -1));
        jPanel8.add(txtNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, -1));
        jPanel8.add(txtCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 90, -1));

        CboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento", "mansion" }));
        jPanel8.add(CboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 90, -1));
        jPanel8.add(txtPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 90, -1));

        btnActualizar1.setText("Actualizar");
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });
        jPanel8.add(btnActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        btnLimpiar.setText("Cancelar");
        jPanel8.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        jPanel9.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 40, -1, -1));

        btnSeleccionarImagen1.setText("Seleccionar Imagen");
        btnSeleccionarImagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarImagen1ActionPerformed(evt);
            }
        });
        jPanel8.add(btnSeleccionarImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, 40));

        txtDescripcion1.setColumns(20);
        txtDescripcion1.setRows(5);
        jScrollPane6.setViewportView(txtDescripcion1);

        jPanel8.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 244, -1));

        jimagen2.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jimagen2Layout = new javax.swing.GroupLayout(jimagen2);
        jimagen2.setLayout(jimagen2Layout);
        jimagen2Layout.setHorizontalGroup(
            jimagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        jimagen2Layout.setVerticalGroup(
            jimagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanel8.add(jimagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 210, 190));
        jPanel8.add(txtDireccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 60, -1));

        TbpPanel1.addTab("Editar", jPanel8);

        jPanel6.add(TbpPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 770, 450));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Editar Inmueble");
        jLabel20.setToolTipText("");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private TableRowSorter trs;
    private void txtBuscar1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar1KeyTyped
        // TODO add your handling code here:
        txtBuscar1.addKeyListener(new KeyAdapter(){
            public void KeyReleased(KeyEvent e){
                String cadena = (txtBuscar1.getText()).toUpperCase();
                txtBuscar1.setText(cadena);
                repaint();
                filtro();
            }
        });
        trs=new TableRowSorter(modelo);
        tbinmueble1.setRowSorter(trs);

    }//GEN-LAST:event_txtBuscar1KeyTyped

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        // TODO add your handling code here:
        ClsInmuebleE objInmE=new  ClsInmuebleE();
        ClsInmuebleN objInmN=new ClsInmuebleN();
        objInmE.setInmuebleid(Integer.parseInt(txtId1.getText()));
        objInmE.setDireccioninmueble(txtDireccion1.getText());
        objInmE.setEstado("Nopublicado");
        objInmE.setNrohabitaciones(Integer.parseInt(txtNumero1.getText()));
        objInmE.setCiudad(txtCiudad1.getText());
        objInmE.setDescripcion(txtDescripcion1.getText());
        objInmE.setCategoria((String)CboCategoria.getSelectedItem());
        objInmE.setPrecio(Double.parseDouble(txtPrecio1.getText()));
        File foto = new File(txtDireccion2.getText());
        try{
            byte[] icono = new byte[(int) foto.length()];
            InputStream input = new FileInputStream(foto);
            input.read(icono);
            objInmE.setFoto(icono);
        }catch(Exception ex){
            objInmE.setFoto(null);
        }
        if (objInmN.MtdActulizarInmueble(objInmE)== true) {
            JOptionPane.showMessageDialog(null, "Dato Actualizados Correctamente...");
            MtdLimpiar();
            MtdListarInmueble();
        }else{
            JOptionPane.showMessageDialog(null, "Error de Datos...");
        }
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    private void tbinmueble1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbinmueble1MouseClicked
        // TODO add your handling code here:
        seleccion = tbinmueble1.rowAtPoint(evt.getPoint());
        txtId1.setText(String.valueOf(tbinmueble1.getValueAt(seleccion,0)));
        txtDireccion1.setText(String.valueOf(tbinmueble1.getValueAt(seleccion,1)));
        txtCiudad1.setText(String.valueOf(tbinmueble1.getValueAt(seleccion,2)));
        txtNumero1.setText(String.valueOf(tbinmueble1.getValueAt(seleccion,5)));
        txtDescripcion1.setText(String.valueOf(tbinmueble1.getValueAt(seleccion,4)));
        txtPrecio1.setText(String.valueOf(tbinmueble1.getValueAt(seleccion,6)));
        Foto = (JLabel) tbinmueble1.getValueAt(seleccion, 7);
        
        ImageIcon iconImage = (ImageIcon) Foto.getIcon();
        Image imgJL = iconImage.getImage().getScaledInstance(jimagen2.getWidth(), jimagen2.getHeight(), Image.SCALE_SMOOTH);
        jimagen2.setIcon(new ImageIcon(imgJL));
        
        
        
    }//GEN-LAST:event_tbinmueble1MouseClicked
File archivo;
    private void btnSeleccionarImagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImagen1ActionPerformed
        // TODO add your handling code here:
        int resultado;
        FrmImagen Buscador =new FrmImagen();
        FileNameExtensionFilter formato  = new FileNameExtensionFilter("JPG, PNG y GIF", "jpg", "png", "gif");
        Buscador.JFCImg.setFileFilter(formato);
        resultado = Buscador.JFCImg.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado){
            archivo = Buscador.JFCImg.getSelectedFile();
            txtDireccion2.setText(archivo.getAbsolutePath());

            try {
                ImageIcon ImgIcon = new ImageIcon(archivo.toString());
                Icon icono = new ImageIcon(ImgIcon.getImage().getScaledInstance(jimagen2.getWidth(), jimagen2.getHeight(),Image.SCALE_DEFAULT));
                jimagen2.setIcon(icono);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Error al abrir: " + e);
            }
        }
    }//GEN-LAST:event_btnSeleccionarImagen1ActionPerformed

String filtro;
    public void filtro() {
    filtro = txtBuscar1.getText();
    trs.setRowFilter(RowFilter.regexFilter(txtBuscar1.getText(), 0));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboCategoria;
    private javax.swing.JCheckBox ChkSeleccionar;
    private javax.swing.JTabbedPane TbpPanel;
    private javax.swing.JTabbedPane TbpPanel1;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSeleccionarImagen;
    private javax.swing.JButton btnSeleccionarImagen1;
    private javax.swing.JComboBox<String> cboCategoria;
    private LIB.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private LIB.JEImagePanel jimagen2;
    private javax.swing.JTable tbinmueble;
    private javax.swing.JTable tbinmueble1;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscar1;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCiudad1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextArea txtDescripcion1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtDireccion2;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecio1;
    // End of variables declaration//GEN-END:variables

    private void MtdLimpiar() {
        txtDescripcion1.setText("");
        txtDireccion1.setText("");
        txtId1.setText("");
        txtNumero1.setText("");
        txtPrecio1.setText("");
        txtCiudad1.setText("");
    }

    private void MtdListarInmueble() {
        modelo=new  DefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("DireccionInmueble");
        modelo.addColumn("Ciudad");
        modelo.addColumn("estado");
        modelo.addColumn("Descripcion");
        modelo.addColumn("NumHabitaciones");
        modelo.addColumn("Precio");
        modelo.addColumn("Foto");

        ClsInmuebleN objInmN=new ClsInmuebleN();
         Object[] datos=new Object[8];
        for (ClsInmuebleE objInmE : objInmN.MtdListarInmueble()) {
            datos[0]=String.valueOf(objInmE.getInmuebleid());
            datos[1]=objInmE.getDireccioninmueble();
            datos[2]=objInmE.getCiudad();
            datos[3]=objInmE.getEstado();
            datos[4]=objInmE.getDescripcion();
            datos[5]=(String.valueOf(objInmE.getNrohabitaciones()));
            datos[6]=(String.valueOf(objInmE.getPrecio()));
            try{
                    byte[] bi = objInmE.getFoto();
                    BufferedImage image = null;
                    InputStream in = new ByteArrayInputStream(bi);
                    image = ImageIO.read(in);
                    ImageIcon imgi = new ImageIcon(image.getScaledInstance(60, 60, 0));
                    datos[7] = new JLabel(imgi);

                }catch(Exception ex){
                    datos[7] = new JLabel("No imagen");
                }
            modelo.addRow(datos);
        }
        this.tbinmueble1.setModel(modelo);
        tbinmueble1.setRowHeight(100);
    }
}
