/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PgkPresentacion;

import PkgEntidad.ClsPersonaE;
import PkgEntidad.ClsUsuarioE;
import PkgNegocio.ClsPersonaN;
import PkgNegocio.ClsUsuarioN;
import static PkgNegocio.ClsUsuarioN.MtdListarUsuario;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author smoke
 */
public class FrmGestionarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmGestionarUuario1
     */
    public DefaultTableModel modelo;
    public DefaultTableModel modelo2;
    public static int seleccion;
    public static int seleccion2;
    public static int idpersona;
    public FrmGestionarUsuario() {
        initComponents();
        modelo=new  DefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("DNI");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");
        modelo.addColumn("EMAIL");
        modelo.addColumn("CELULAR");
        modelo.addColumn("DIRECCION");
        ClsPersonaN objPerN=new ClsPersonaN();
        String[] datos=new String[7];
        for (ClsPersonaE objPerE : objPerN.MtdListarPersona()) {
            datos[0]=String.valueOf(objPerE.getPersonaid());
            datos[1]=objPerE.getDni();
            datos[2]=objPerE.getNombre();
            datos[3]=objPerE.getApellido();
            datos[4]=objPerE.getEmail();
            datos[5]=objPerE.getCelular();
            datos[6]=objPerE.getDireccion();
            modelo.addRow(datos);
        }
        this.tbpersona.setModel(modelo);
        
       
        MtdListarUsuario2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbpersona = new javax.swing.JTable();
        txtBuscar = new LIB.FSTexFieldMD();
        fSTexFieldMD7 = new LIB.FSTexFieldMD();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new LIB.FSTexFieldMD();
        txtUsuario = new LIB.FSTexFieldMD();
        txtClave = new LIB.FSTexFieldMD();
        cboxNivel = new javax.swing.JComboBox<>();
        btnLimpiar = new LIB.FSButtonMD();
        btnAgregarUsu = new LIB.FSButtonMD();
        btnActualizar = new LIB.FSButtonMD();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbusuario = new javax.swing.JTable();
        btnActivar1 = new LIB.FSButtonMD();
        btnDesactivar1 = new LIB.FSButtonMD();
        jLabel8 = new javax.swing.JLabel();
        txtID1 = new LIB.FSTexFieldMD();
        cboxEstado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gestionar Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setText("Buscar");
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        tbpersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbpersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpersonaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbpersona);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 750, 290));

        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBordeColorFocus(new java.awt.Color(51, 51, 255));
        txtBuscar.setPlaceholder("");
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        jPanel2.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 240, 30));

        fSTexFieldMD7.setForeground(new java.awt.Color(0, 0, 0));
        fSTexFieldMD7.setBordeColorFocus(new java.awt.Color(51, 51, 255));
        fSTexFieldMD7.setPlaceholder("");
        jPanel2.add(fSTexFieldMD7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 240, 30));

        jLabel7.setText("Buscar:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jTabbedPane1.addTab("Listar", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Id Persona:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jLabel4.setText("Usuario:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        jLabel5.setText("Clave:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jLabel6.setText("Estado:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        txtId.setEditable(false);
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.setBordeColorFocus(new java.awt.Color(0, 0, 255));
        txtId.setPlaceholder("0");
        jPanel3.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 220, 40));

        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setBordeColorFocus(new java.awt.Color(0, 0, 255));
        txtUsuario.setPlaceholder("Jperez");
        jPanel3.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 220, 40));

        txtClave.setForeground(new java.awt.Color(0, 0, 0));
        txtClave.setBordeColorFocus(new java.awt.Color(0, 0, 255));
        txtClave.setPlaceholder("*************");
        jPanel3.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 220, 40));

        cboxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arrendatario", "Arrendador" }));
        cboxNivel.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(cboxNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 220, 30));

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setColorNormal(new java.awt.Color(0, 0, 0));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 90, -1));

        btnAgregarUsu.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarUsu.setText("Agregar");
        btnAgregarUsu.setColorNormal(new java.awt.Color(0, 0, 0));
        btnAgregarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizar.setText("Actualizar");
        btnActualizar.setColorNormal(new java.awt.Color(0, 0, 0));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 80, -1));

        tbusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbusuarioMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbusuario);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 430, 310));

        btnActivar1.setBackground(new java.awt.Color(0, 0, 0));
        btnActivar1.setText("Activar");
        btnActivar1.setColorNormal(new java.awt.Color(0, 0, 0));
        jPanel3.add(btnActivar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 120, 30));

        btnDesactivar1.setBackground(new java.awt.Color(0, 0, 0));
        btnDesactivar1.setText("Desactivar");
        btnDesactivar1.setColorNormal(new java.awt.Color(0, 0, 0));
        jPanel3.add(btnDesactivar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 110, 30));

        jLabel8.setText("ID:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        txtID1.setEditable(false);
        txtID1.setForeground(new java.awt.Color(0, 0, 0));
        txtID1.setBordeColorFocus(new java.awt.Color(51, 51, 255));
        txtID1.setPlaceholder("");
        jPanel3.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 80, 40));

        cboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cboxEstado.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(cboxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 130, 30));

        jLabel9.setText("Nivel:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 20));

        jTabbedPane1.addTab("Agregar", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 780, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbpersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpersonaMouseClicked
        // TODO add your handling code here:
        seleccion = tbpersona.rowAtPoint(evt.getPoint());
        txtId.setText(String.valueOf(tbpersona.getValueAt(seleccion,0)));
    }//GEN-LAST:event_tbpersonaMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        MtdLimpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuActionPerformed
        // TODO add your handling code here:
        ClsUsuarioE objUsuE=new  ClsUsuarioE();
        ClsUsuarioN objUsuN=new ClsUsuarioN();
        objUsuE.setPersonaid(Integer.parseInt(txtId.getText()));
        objUsuE.setNombreusuario(txtUsuario.getText());
        objUsuE.setClave(txtClave.getText());
        objUsuE.setNivel((String)cboxNivel.getSelectedItem());
        objUsuE.setEstado("Activo");
        if (objUsuN.MtdRegistrarUsuario(objUsuE)== true) {
            JOptionPane.showMessageDialog(null, "Dato Guardados Correctamente...");
            MtdLimpiar();
            MtdListarUsuario2();
        }else{
            JOptionPane.showMessageDialog(null, "Error de Datos...");
        }
    }//GEN-LAST:event_btnAgregarUsuActionPerformed

    private void tbusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbusuarioMouseClicked
        // TODO add your handling code here:
        seleccion2 = tbusuario.rowAtPoint(evt.getPoint());
        txtId.setText(String.valueOf(tbusuario.getValueAt(seleccion2,1)));
        txtID1.setText(String.valueOf(tbusuario.getValueAt(seleccion2,0)));
        txtUsuario.setText(String.valueOf(tbusuario.getValueAt(seleccion2,2)));
        cboxNivel.setSelectedItem(String.valueOf(tbusuario.getValueAt(seleccion2,3)));
        cboxEstado.setSelectedItem(String.valueOf(tbusuario.getValueAt(seleccion2,4)));
    }//GEN-LAST:event_tbusuarioMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
         ClsUsuarioE objUsuE=new  ClsUsuarioE();
        ClsUsuarioN objUsuN=new ClsUsuarioN();
        objUsuE.setUsuarioid(Integer.parseInt(txtID1.getText()));
        objUsuE.setNombreusuario(txtUsuario.getText());
        objUsuE.setClave(txtClave.getText());
        objUsuE.setNivel((String)cboxNivel.getSelectedItem());
        objUsuE.setEstado((String)cboxEstado.getSelectedItem());
        if (objUsuN.MtdActualizarUsuario(objUsuE)== true) {
            JOptionPane.showMessageDialog(null, "Dato Actulizados Correctamente...");
            MtdLimpiar();
            MtdListarUsuario2();
        }else{
            JOptionPane.showMessageDialog(null, "Error de Datos...");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed
private TableRowSorter trs;
    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        // TODO add your handling code here:
        txtBuscar.addKeyListener(new KeyAdapter(){
            public void KeyReleased(KeyEvent e){
                String cadena = (txtBuscar.getText()).toUpperCase();
                txtBuscar.setText(cadena);
                repaint();
                filtro();
            }
        });
        trs=new TableRowSorter(modelo);
        tbpersona.setRowSorter(trs);
    }//GEN-LAST:event_txtBuscarKeyTyped
String filtro;
    public void filtro() {
    filtro = txtBuscar.getText();
    trs.setRowFilter(RowFilter.regexFilter(txtBuscar.getText(), 0));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btnActivar1;
    private LIB.FSButtonMD btnActualizar;
    private LIB.FSButtonMD btnAgregarUsu;
    private javax.swing.JButton btnBuscar;
    private LIB.FSButtonMD btnDesactivar1;
    private LIB.FSButtonMD btnLimpiar;
    private javax.swing.JComboBox<String> cboxEstado;
    private javax.swing.JComboBox<String> cboxNivel;
    private LIB.FSTexFieldMD fSTexFieldMD7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbpersona;
    private javax.swing.JTable tbusuario;
    private LIB.FSTexFieldMD txtBuscar;
    private LIB.FSTexFieldMD txtClave;
    private LIB.FSTexFieldMD txtID1;
    private LIB.FSTexFieldMD txtId;
    private LIB.FSTexFieldMD txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void MtdLimpiar() {
        txtID1.setText("");
        txtId.setText("");
        txtUsuario.setText("");
        txtClave.setText("");
    }

    private void MtdListarUsuario2() {
        modelo2=new  DefaultTableModel();
        modelo2.addColumn("CODIGO");
        modelo2.addColumn("ID_PERSONA");
        modelo2.addColumn("USUARIO");
        modelo2.addColumn("NIVEL");
        modelo2.addColumn("ESTADO");
        ClsUsuarioN objUsuN=new ClsUsuarioN();
        String[] datos1=new String[5];
        for (ClsUsuarioE objUsuE : objUsuN.MtdListarUsuario()) {
            datos1[0]=String.valueOf(objUsuE.getUsuarioid());
            datos1[1]=String.valueOf(objUsuE.getPersonaid());
            datos1[2]=objUsuE.getNombreusuario();
            datos1[3]=objUsuE.getNivel();
            datos1[4]=objUsuE.getEstado();
            modelo2.addRow(datos1);
        }
        this.tbusuario.setModel(modelo2);
    }
}
