/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PgkPresentacion;

import PkgEntidad.ClsInmuebleE;
import PkgNegocio.ClsInmuebleN;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author smoke
 */
public class FrmInmueblesPublicados extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmInmueblesPublicados1
     */
    public DefaultTableModel modelo;
    public static int id;
    public FrmInmueblesPublicados() {
        initComponents();
        tbInmueble.setDefaultRenderer(Object.class,new RenderTabla());
        modelo=new  DefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("COD_USUARIO");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("ESTADO");
        modelo.addColumn("NroHABITACIONES");
        modelo.addColumn("CIUDAD");
        modelo.addColumn("DESCRIOCION");
        modelo.addColumn("CATEGORIA");
        modelo.addColumn("PRECIO");
        modelo.addColumn("FOTO");
        ClsInmuebleN objInmuebleN=new ClsInmuebleN();
       ClsInmuebleE objInmE=new ClsInmuebleE();
       objInmE.setUsuarioid(id);
        Object[] datos=new Object[10];
        for (ClsInmuebleE objInmuebleE : objInmuebleN.MtdListarInmueblePublicadoUsu(objInmE)) {
            datos[0]=String.valueOf(objInmuebleE.getInmuebleid());
            datos[1]=String.valueOf(objInmuebleE.getUsuarioid());
            datos[2]=objInmuebleE.getDireccioninmueble();
            datos[3]=objInmuebleE.getEstado();
            datos[4]=String.valueOf(objInmuebleE.getNrohabitaciones());
            datos[5]=objInmuebleE.getCiudad();
            datos[6]=objInmuebleE.getDescripcion();
            datos[7]=objInmuebleE.getCategoria();
            datos[8]=String.valueOf(objInmuebleE.getPrecio());
            
            try{
                    byte[] bi = objInmuebleE.getFoto();
                    BufferedImage image = null;
                    InputStream in = new ByteArrayInputStream(bi);
                    image = ImageIO.read(in);
                    ImageIcon imgi = new ImageIcon(image.getScaledInstance(60, 60, 0));
                    datos[9] = new JLabel(imgi);

                }catch(Exception ex){
                    datos[9] = new JLabel("No imagen");
                }
            modelo.addRow(datos);
        }
        this.tbInmueble.setModel(modelo);
        tbInmueble.setRowHeight(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInmueble = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbInmueble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbInmueble);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 710, 390));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Visualizar Inmuebles Publicados ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 306, 52));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbInmueble;
    // End of variables declaration//GEN-END:variables

   
}
