/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PgkPresentacion;

import PkgEntidad.ClsInmuebleE;
import PkgEntidad.ClsPersonaE;
import PkgNegocio.ClsInmuebleN;
import PkgNegocio.ClsPersonaN;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author smoke
 */
public class FrmPublicarInmueble extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmPublicarInmueble1
     */
    public static int seleccion;
    public DefaultTableModel modelo;
    public FrmPublicarInmueble() {
        initComponents();
        tbinmueble.setDefaultRenderer(Object.class,new RenderTabla());
        MtdListarNopublicados();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbinmueble = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtId = new LIB.FSTexFieldMD();
        txtDireccion = new LIB.FSTexFieldMD();
        txtNumHabitaciones = new LIB.FSTexFieldMD();
        txtCiudad = new LIB.FSTexFieldMD();
        txtPrecio = new LIB.FSTexFieldMD();
        jLabel8 = new javax.swing.JLabel();
        txtTipo = new LIB.FSTexFieldMD();
        btnPublicarInmueble = new LIB.FSButtonMD();
        jEImagePanel1 = new LIB.JEImagePanel();
        jLabel9 = new javax.swing.JLabel();
        txtDescripcion = new LIB.FSTexFieldMD();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Publicar Inmueble");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 310, 50));

        tbinmueble.setBorder(new javax.swing.border.MatteBorder(null));
        tbinmueble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbinmueble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbinmuebleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbinmueble);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 760, 190));

        jLabel2.setText("Id Inmueble:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel3.setText("Direccion:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel4.setText("Nro de Habitaciones:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel5.setText("Ciudad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel6.setText("Tipo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        jLabel7.setText("Descripcion:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        txtId.setEditable(false);
        txtId.setForeground(new java.awt.Color(51, 51, 51));
        txtId.setBordeColorFocus(new java.awt.Color(102, 153, 255));
        txtId.setPlaceholder("0");
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 160, 40));

        txtDireccion.setEditable(false);
        txtDireccion.setForeground(new java.awt.Color(51, 51, 51));
        txtDireccion.setBordeColorFocus(new java.awt.Color(102, 153, 255));
        txtDireccion.setPlaceholder("Av. Pinto 1000");
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 160, 40));

        txtNumHabitaciones.setEditable(false);
        txtNumHabitaciones.setForeground(new java.awt.Color(51, 51, 51));
        txtNumHabitaciones.setBordeColorFocus(new java.awt.Color(102, 153, 255));
        txtNumHabitaciones.setPlaceholder("2");
        jPanel1.add(txtNumHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 160, 40));

        txtCiudad.setEditable(false);
        txtCiudad.setForeground(new java.awt.Color(51, 51, 51));
        txtCiudad.setBordeColorFocus(new java.awt.Color(102, 153, 255));
        txtCiudad.setPlaceholder("Tacna");
        jPanel1.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 160, 40));

        txtPrecio.setEditable(false);
        txtPrecio.setForeground(new java.awt.Color(51, 51, 51));
        txtPrecio.setBordeColorFocus(new java.awt.Color(102, 153, 255));
        txtPrecio.setPlaceholder("S/. 999");
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 160, 40));

        jLabel8.setText("Precio:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        txtTipo.setEditable(false);
        txtTipo.setForeground(new java.awt.Color(51, 51, 51));
        txtTipo.setBordeColorFocus(new java.awt.Color(102, 153, 255));
        txtTipo.setPlaceholder("Departamento");
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 160, 40));

        btnPublicarInmueble.setBackground(new java.awt.Color(0, 0, 0));
        btnPublicarInmueble.setBorder(new javax.swing.border.MatteBorder(null));
        btnPublicarInmueble.setText("Publicar Inmueble");
        btnPublicarInmueble.setColorNormal(new java.awt.Color(0, 0, 0));
        btnPublicarInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicarInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(btnPublicarInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, -1, -1));

        jEImagePanel1.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jEImagePanel1Layout = new javax.swing.GroupLayout(jEImagePanel1);
        jEImagePanel1.setLayout(jEImagePanel1Layout);
        jEImagePanel1Layout.setHorizontalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jEImagePanel1Layout.setVerticalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        jPanel1.add(jEImagePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 160, 160));

        jLabel9.setText("Imagen");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, -1, -1));

        txtDescripcion.setEditable(false);
        txtDescripcion.setForeground(new java.awt.Color(51, 51, 51));
        txtDescripcion.setBordeColorFocus(new java.awt.Color(102, 153, 255));
        txtDescripcion.setPlaceholder("Departamento");
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 160, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbinmuebleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbinmuebleMouseClicked
        // TODO add your handling code here:
        seleccion = tbinmueble.rowAtPoint(evt.getPoint());
        txtId.setText(String.valueOf(tbinmueble.getValueAt(seleccion,0)));
        txtDireccion.setText(String.valueOf(tbinmueble.getValueAt(seleccion,2)));
        txtNumHabitaciones.setText(String.valueOf(tbinmueble.getValueAt(seleccion,4)));
        txtCiudad.setText(String.valueOf(tbinmueble.getValueAt(seleccion,5)));
        txtDescripcion.setText(String.valueOf(tbinmueble.getValueAt(seleccion,6)));
        txtTipo.setText(String.valueOf(tbinmueble.getValueAt(seleccion,7)));
        txtPrecio.setText(String.valueOf(tbinmueble.getValueAt(seleccion,8)));
        
    }//GEN-LAST:event_tbinmuebleMouseClicked

    private void btnPublicarInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicarInmuebleActionPerformed
        // TODO add your handling code here:
        ClsInmuebleE objInmE=new  ClsInmuebleE();
        ClsInmuebleN objInmN=new ClsInmuebleN();
        objInmE.setInmuebleid(Integer.parseInt(txtId.getText()));
        objInmE.setEstado("Publicado");
        if (objInmN.MtdAcPublicarInmueble(objInmE)== true) {
            JOptionPane.showMessageDialog(null, "Inmueble Publicado Correctamente...");
            MtdLimpiar();
            MtdListarNopublicados();
        }else{
            JOptionPane.showMessageDialog(null, "Error de Datos...");
        }
        
    }//GEN-LAST:event_btnPublicarInmuebleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btnPublicarInmueble;
    private LIB.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbinmueble;
    private LIB.FSTexFieldMD txtCiudad;
    private LIB.FSTexFieldMD txtDescripcion;
    private LIB.FSTexFieldMD txtDireccion;
    private LIB.FSTexFieldMD txtId;
    private LIB.FSTexFieldMD txtNumHabitaciones;
    private LIB.FSTexFieldMD txtPrecio;
    private LIB.FSTexFieldMD txtTipo;
    // End of variables declaration//GEN-END:variables

    private void MtdListarNopublicados() {
        modelo=new  DefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("COD_USUARIO");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("ESTADO");
        modelo.addColumn("NroHABITACIONES");
        modelo.addColumn("CIUDAD");
        modelo.addColumn("DESCRIOCION");
        modelo.addColumn("CATEGORIA");
        modelo.addColumn("PRECIO");
        modelo.addColumn("FOTO");
        ClsInmuebleN objInmuebleN=new ClsInmuebleN();
        Object[] datos=new Object[10];
        for (ClsInmuebleE objInmE : objInmuebleN.MtdListarInmuebleNoPublicado()) {
            datos[0]=String.valueOf(objInmE.getInmuebleid());
            datos[1]=String.valueOf(objInmE.getUsuarioid());
            datos[2]=objInmE.getDireccioninmueble();
            datos[3]=objInmE.getEstado();
            datos[4]=String.valueOf(objInmE .getNrohabitaciones());
            datos[5]=objInmE.getCiudad();
            datos[6]=objInmE.getDescripcion();
            datos[7]=objInmE.getCategoria();
            datos[8]=String.valueOf(objInmE.getPrecio());
            
            try{
                    byte[] bi = objInmE.getFoto();
                    BufferedImage image = null;
                    InputStream in = new ByteArrayInputStream(bi);
                    image = ImageIO.read(in);
                    ImageIcon imgi = new ImageIcon(image.getScaledInstance(60, 60, 0));
                    datos[9] = new JLabel(imgi);

                }catch(Exception ex){
                    datos[9] = new JLabel("No imagen");
                }
            modelo.addRow(datos);
        }
        this.tbinmueble.setModel(modelo);
    }

    private void MtdLimpiar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
