/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PgkPresentacion;

import PkgEntidad.ClsPersonaE;
import PkgNegocio.ClsPersonaN;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author smoke
 */
public class FrmRegistrarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmRegistrarUsuario1
     */
    public FrmRegistrarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAgregar = new LIB.FSButtonMD();
        txtDni = new LIB.FSTexFieldMD();
        txtNombre = new LIB.FSTexFieldMD();
        txtCelular = new LIB.FSTexFieldMD();
        txtEmail = new LIB.FSTexFieldMD();
        txtDireccion = new LIB.FSTexFieldMD();
        txtApellido = new LIB.FSTexFieldMD();
        btnLimpiar = new LIB.FSButtonMD();
        jPanel1 = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Registrar Persona");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel2.setText("Nombre: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel3.setText("Nro Celular:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel4.setText("  Emai:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel5.setText("Direccion:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel6.setText("Apellidos:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        jLabel7.setText("Dni:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("Agregar");
        btnAgregar.setColorNormal(new java.awt.Color(0, 0, 0));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 130, 40));

        txtDni.setForeground(new java.awt.Color(0, 0, 0));
        txtDni.setBordeColorFocus(new java.awt.Color(51, 0, 255));
        txtDni.setPlaceholder("78945612");
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });
        jPanel2.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 190, 50));

        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setAutoscrolls(false);
        txtNombre.setBordeColorFocus(new java.awt.Color(51, 0, 255));
        txtNombre.setPlaceholder("Juan");
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 190, 50));

        txtCelular.setForeground(new java.awt.Color(0, 0, 0));
        txtCelular.setBordeColorFocus(new java.awt.Color(51, 0, 255));
        txtCelular.setPlaceholder("987654321");
        jPanel2.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 190, 50));

        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setBordeColorFocus(new java.awt.Color(51, 0, 255));
        txtEmail.setPlaceholder("Juan_Perez@hotmail.com");
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 190, 50));

        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccion.setBordeColorFocus(new java.awt.Color(51, 0, 255));
        txtDireccion.setPlaceholder("Av. Los mirones 554");
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 190, 50));

        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setBordeColorFocus(new java.awt.Color(51, 0, 255));
        txtApellido.setPlaceholder("Perez Perez");
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 190, 50));

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setColorNormal(new java.awt.Color(0, 0, 0));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 130, 40));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        ClsPersonaE objPerE=new  ClsPersonaE();
        ClsPersonaN objPerN=new ClsPersonaN();
        objPerE.setNombre(txtNombre.getText());
        objPerE.setApellido(txtApellido.getText());
        objPerE.setDni(txtDni.getText());
        objPerE.setEmail(txtEmail.getText());
        objPerE.setCelular(txtCelular.getText());
        objPerE.setDireccion(txtDireccion.getText());
        if (objPerN.MtdRegistrarPersona(objPerE)== true) {
            JOptionPane.showMessageDialog(null, "Dato Guardados Correctamente...");
            MtdLimpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Error de Datos...");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
        // TODO add your handling code here:
        String leerdni =txtDni.getText();
        String enlace   = "https://api.reniec.cloud/dni/"+leerdni;
        try {
            URL url = new  URL(enlace);
            URLConnection request = url.openConnection();
            request.connect();

            JsonParser jp = new JsonParser();
            JsonElement root = jp.parse(new InputStreamReader((InputStream)request.getContent()));
            if (root.isJsonObject()){
                JsonObject rootobj = root.getAsJsonObject();
                String apellido_paterno = rootobj.get("Apellido_paterno").getAsString();
                String apellido_materno = rootobj.get("Apellido_materno").getAsString();
                String nombres = rootobj.get("nombres").getAsString();
                txtNombre.setText(nombres);
                txtApellido.setText(apellido_paterno+apellido_materno);

            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_txtDniKeyTyped

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        MtdLimpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed
     private void MtdLimpiar() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtDni.setText("");
        txtCelular.setText("");
        txtEmail.setText("");
        txtDireccion.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btnAgregar;
    private LIB.FSButtonMD btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private LIB.FSTexFieldMD txtApellido;
    private LIB.FSTexFieldMD txtCelular;
    private LIB.FSTexFieldMD txtDireccion;
    private LIB.FSTexFieldMD txtDni;
    private LIB.FSTexFieldMD txtEmail;
    private LIB.FSTexFieldMD txtNombre;
    // End of variables declaration//GEN-END:variables
}

