/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PgkPresentacion;

import PkgEntidad.ClsReservaE;
import PkgNegocio.ClsReservaN;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author smoke
 */
public class FrmReservasInmuebles extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmReservasInmuebles1
     */
    public static int seleccion;
    public DefaultTableModel modelo;
    public static int id = 0;
    public static String Tipousu;
    public FrmReservasInmuebles() {
        initComponents();
        if (Tipousu.equals("Arrendatario")) {
             MtdReservasUsuario();
             cboEstado.setVisible(false);
             btnAceptar.setVisible(false);
        }
        else if (Tipousu.equals("Arrendador")) {
             MtdReservasArrendadot();
        }
      
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TbpPanel = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabLista = new javax.swing.JTable();
        btnAceptar = new LIB.FSButtonMD();
        cboEstado = new javax.swing.JComboBox<>();
        txtId = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TbpPanel.setBorder(new javax.swing.border.MatteBorder(null));
        TbpPanel.setName("editar"); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Buscar:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 252, -1));

        btnBuscar.setText("Buscar");
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        TabLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabListaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TabLista);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 740, 260));

        btnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar.setBorder(new javax.swing.border.MatteBorder(null));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 110, -1));

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aceptado", "Rechazado" }));
        jPanel3.add(cboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 110, 30));

        txtId.setEditable(false);
        txtId.setText("0");
        jPanel3.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 30, -1));

        TbpPanel.addTab("Listar", jPanel3);

        jPanel2.add(TbpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 780, 450));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESERVAS DE INMUEBLE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addContainerGap(538, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        ClsReservaE objReE=new  ClsReservaE();
        ClsReservaN objReN=new ClsReservaN();
        objReE.setReserva_id(Integer.parseInt(txtId.getText()));
        objReE.setEstado((String)cboEstado.getSelectedItem());
        if (objReN.MtdAceptarInmueble(objReE)== true) {
            JOptionPane.showMessageDialog(null, "Reserva Acepta Correctamente...");
            
            MtdReservasArrendadot();
        }else{
            JOptionPane.showMessageDialog(null, "Error de Datos...");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void TabListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabListaMouseClicked
        // TODO add your handling code here:
        seleccion = TabLista.rowAtPoint(evt.getPoint());
        txtId.setText(String.valueOf(TabLista.getValueAt(seleccion,0)));
    }//GEN-LAST:event_TabListaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabLista;
    private javax.swing.JTabbedPane TbpPanel;
    private LIB.FSButtonMD btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

    private void MtdReservasUsuario() {
        modelo=new  DefaultTableModel();
        modelo.addColumn("RESERVA_ID");
        modelo.addColumn("INMUEBLE_ID");
        modelo.addColumn("FECHA_INICIO");
        modelo.addColumn("FECHA_FINAL");
        modelo.addColumn("ESTADO");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("ID_PERSONA");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("CELULAR");
        ClsReservaN objResN=new ClsReservaN();
        ClsReservaE objResvE=new ClsReservaE();
        objResvE.setPersona_id(id);
        String[] datos=new String[10];
        for (ClsReservaE objResE : objResN.MtdListarReservaUsu(objResvE)) {
            datos[0]=String.valueOf(objResE.getReserva_id());
            datos[1]=String.valueOf(objResE.getInmueble_id());
            datos[2]=String.valueOf(objResE.getFechaI());
            datos[3]=String.valueOf(objResE.getFechF());
            datos[4]=objResE.getEstado();
            datos[5]=String.valueOf(objResE.getDescripcion());
            datos[6]=String.valueOf(objResE.getPersona_id());
            datos[7]=objResE.getNombre();
            datos[8]=objResE.getCelular();
            datos[9]=String.valueOf(objResE.getIdusu());
            modelo.addRow(datos);
        }
        this.TabLista.setModel(modelo);
    }

    private void MtdReservasArrendadot() {
         modelo=new  DefaultTableModel();
        modelo.addColumn("RESERVA_ID");
        modelo.addColumn("INMUEBLE_ID");
        modelo.addColumn("FECHA_INICIO");
        modelo.addColumn("FECHA_FINAL");
        modelo.addColumn("ESTADO");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("ID_PERSONA");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("CELULAR");
        ClsReservaN objResN=new ClsReservaN();
        ClsReservaE objResvE=new ClsReservaE();
        objResvE.setPersona_id(id);
        String[] datos=new String[10];
        for (ClsReservaE objResE : objResN.MtdListarReservaArre(objResvE)) {
            datos[0]=String.valueOf(objResE.getReserva_id());
            datos[1]=String.valueOf(objResE.getInmueble_id());
            datos[2]=String.valueOf(objResE.getFechaI());
            datos[3]=String.valueOf(objResE.getFechF());
            datos[4]=objResE.getEstado();
            datos[5]=String.valueOf(objResE.getDescripcion());
            datos[6]=String.valueOf(objResE.getPersona_id());
            datos[7]=objResE.getNombre();
            datos[8]=objResE.getCelular();
            datos[9]=String.valueOf(objResE.getIdusu());
            
            modelo.addRow(datos);
        }
        this.TabLista.setModel(modelo);
        TabLista.setRowHeight(100);
    }
}
